### ISSUE TITLE
D1.4.1 Industrial Use Cases for Turkish Consortium

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#8]
- [ ] UC-TR-01 Production of a proposal in response to an IPA Invitation To ModelWriter/WP1#20
- [ ] UC-TR-02 Collaborative production of a proposal for an IPA project ModelWriter/WP1#21
- [x] UC-TR-03 Synchronization of ReqIF/Clafer models from requirement ModelWriter/WP1#22
- [ ] UC-TR-04 Requirement Engineering for System Modelling ModelWriter/WP1#23
- [x] UC-TR-05 Synchronous Business Process Design with Use Cases ModelWriter/WP1#24

https://github.com/ModelWriter/WP1/blob/master/Deliverables/D1.4.1%20Industrial%20Use%20Cases%20for%20Turkish%20Consortium.docx
