### ISSUE TITLE
D6.1.1 Prototype Core ModelWriter

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#82]
## This is an issue of the task : T6.1 Experimental Prototyping (OBEO + UNIT)

This is an initial step especially foreseen to address the technical risk: selection and adaptation (e.g. wrapping) of the existing core components to be integrated within Eclipse for providing the Core ModelWriter, and demonstration of the feasibility of communication between these components:

Word Processor (Documentation Authoring Tool) (UNIT):

Prototype ensuring that it is possible to wrap an existing word processor (like OpenOffice) as an Eclipse Plugin, compatible with the modelling standards of the Eclipse IDE (Eclipse modelling Framework) and able to detect notifications sent by the Bi-directional Synchronization Mechanism. If not, an alternative word processor (e.g. Adobe’s FrameMaker) should be chosen, and the same prototype will have to be developed.
o   Knowledge Base (UNIT):
The complete design of the Knowledge Base is covered by Task T4.1. As the KB is the base of the communication between the ModelWriter components, a first prototype of the Knowledge Base should be developed to achieve the subtasks listed below.
o   Modelling tool (Obeo): Obeo Designer modellers (diagrams, tables and trees)
Obeo Designer enables to easily define graphical modellers for any kind of models (UML, ORM or any kind of DSL) integrated to the Eclipse IDE.
In the ModelWriter’s Use Cases, Obeo Designer is part of the "Model View", and hence should allow users to:
-   Define models using graphical modellers, and then document these models using ModelWriter.
-   Modify the models computed by ModelWriter using the graphical modellers.
  A prototype will be written to ensure Obeo Designer compatibility with other components.
  To ensure that the specifier retrieves his ordinary vision of specifications, the graphical modellers should provide table spreadsheets displaying the models (requirements, concepts defined inside ModelWriter, etc.) in a form similar to OpenOffice tables. Other graphical modellers (like diagrams) will also be provided to allow the specifier to see his specifications (e.g. as Mind Maps).
  o   Bi-Directional Synchronization Mechanism (Obeo) : Intent Open-source project
  A first prototype should prove that Intent can:
-   Provide API allowing interactions with the Writer part and the Model part, so that each of these components can be notified of changes made on documentation or models.
-   Synchronize the models stored inside the Knowledge Base.
  o   ORM editor (UNIT):
  An Eclipse plugin for viewing and editing ORM models and ModelWriter Knowledge Base. In this task, a part of the of DOGMA Studio codebase will be reused to develop an Eclipse plugin for viewing and editing ORM models using the EMF framework. DOGMA Studio was an early Eclipse-based prototype for ontology engineering using only binary fact-types using the ORM notation. Additional plugins and/or libraries will be developed to connect the Eclipse environment and the ORM models with the Knowledge Base.
## the sub-issues are as follows:
- [x] [UC-TR-03] ModelWriter/WP6#13
- [ ] [UC-TR-04] ModelWriter/WP6#14
- [x] [UC-TR-05] ModelWriter/WP6#15

**Comment by mrostren** [comment]
@ferhaterata Can we close this issue ?

**Comment by ferhaterata** [comment]
Not yet, we are still developing the second PoC but almost done! we need +1
days.

Thanks,

On Mon, Mar 16, 2015 at 11:27 AM, mrostren <notifications@github.com> wrote:

> @ferhaterata <https://github.com/ferhaterata> Can we close this issue ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModelWriter/Project-Management/issues/82#issuecomment-81533096>
> .
>



-- 
Ferhat Erata

Project Leader, ITEA-ModelWriter Consortium
PhD Student, Int'l Computer Inst., Ege University, Izmir, Turkey
-
Email: ferhat@computer.org
Skype: ferhat.erata
Mobile: +90-539-5661271
LinkedIn: https://linkedin.com/in/ferhaterata
GitHub: https://github.com/ferhaterata
ModelWriter: http://www.modelwriter.eu

**Comment by ferhaterata** [comment]
@ffurkAn @m-challenger

**Comment by ferhaterata** [comment]
BTW, I need to run the script (which I developed before to create deliverables on GitHub) again to update the new numbering of the deliverables with regards to incoming change request. 

@ModelWriter/consortium

**Comment by ffurkAn** [comment]
I've managed to finished the PoC with some small missing parts such as
creating bulleted lists during conversion from model to docx file and some
design issues. You can see my sample input file and converted output file
attached.

Kind regards



On Mon, Mar 16, 2015 at 11:31 AM, Ferhat Erata <notifications@github.com>
wrote:

> BTW, I need to run the script (which I developed before to create
> deliverables on GitHub) again to update the new numbering of the
> deliverables with regards to incoming change request.
>
> @ModelWriter/consortium
> <https://github.com/orgs/ModelWriter/teams/consortium>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModelWriter/Project-Management/issues/82#issuecomment-81537449>
> .
>



-- 

Abdulbaki Furkan TANRIVERDİ

Ege University Computer Engineering (B.Sc.)
Software Developer at UNIT Information Technologies R&D Ltd.

--
Mobile: +90 545 634 63 65
LinkedIn <https://www.linkedin.com/pub/a-furkan-tanriverdi/78/646/160>

**Comment by mrostren** [comment]
The prototypes are available on github WP6/ release D6.1.1-SoftwarePrototypeCoreModelWriter-M6
The branch D6.1.1-SoftwarePrototypeCoreModelWriter will be always available to update the architecture. 
Please make sure that the D6.1.1-SoftwarePrototypeCoreModelWriterbranch is rebased on the master branch before !
